server:
  port: 10000
eureka:
  client:
    fetch-registry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:10000/eureka
security:
  basic:
    enabled: true #开启验证
  user:
    name: user
    password: 1234