server:
  port: 8900
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:1234@localhost:10000/eureka/
spring:
  application:
    name: conmsumerorder
PROVIDER-USER1:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
