
package com.helen.ws.helloservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyHelloServer", targetNamespace = "helloservice.ws.helen.com", wsdlLocation = "http://127.0.0.1:8089/hello?wsdl")
public class MyHelloServer
    extends Service
{

    private final static URL MYHELLOSERVER_WSDL_LOCATION;
    private final static WebServiceException MYHELLOSERVER_EXCEPTION;
    private final static QName MYHELLOSERVER_QNAME = new QName("helloservice.ws.helen.com", "MyHelloServer");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8089/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYHELLOSERVER_WSDL_LOCATION = url;
        MYHELLOSERVER_EXCEPTION = e;
    }

    public MyHelloServer() {
        super(__getWsdlLocation(), MYHELLOSERVER_QNAME);
    }

    public MyHelloServer(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYHELLOSERVER_QNAME, features);
    }

    public MyHelloServer(URL wsdlLocation) {
        super(wsdlLocation, MYHELLOSERVER_QNAME);
    }

    public MyHelloServer(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYHELLOSERVER_QNAME, features);
    }

    public MyHelloServer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyHelloServer(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MyHello
     */
    @WebEndpoint(name = "MyHelloPort")
    public MyHello getMyHelloPort() {
        return super.getPort(new QName("helloservice.ws.helen.com", "MyHelloPort"), MyHello.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyHello
     */
    @WebEndpoint(name = "MyHelloPort")
    public MyHello getMyHelloPort(WebServiceFeature... features) {
        return super.getPort(new QName("helloservice.ws.helen.com", "MyHelloPort"), MyHello.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYHELLOSERVER_EXCEPTION!= null) {
            throw MYHELLOSERVER_EXCEPTION;
        }
        return MYHELLOSERVER_WSDL_LOCATION;
    }

}
