
package com.helen.ws.helloservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyHello", targetNamespace = "helloservice.ws.helen.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyHello {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayBye", targetNamespace = "helloservice.ws.helen.com", className = "com.helen.ws.helloservice.SayBye")
    @ResponseWrapper(localName = "sayByeResponse", targetNamespace = "helloservice.ws.helen.com", className = "com.helen.ws.helloservice.SayByeResponse")
    @Action(input = "helloservice.ws.helen.com/MyHello/sayByeRequest", output = "helloservice.ws.helen.com/MyHello/sayByeResponse")
    public String sayBye(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "helloResult", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "helloservice.ws.helen.com", className = "com.helen.ws.helloservice.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "helloservice.ws.helen.com", className = "com.helen.ws.helloservice.SayHelloResponse")
    @Action(input = "helloservice.ws.helen.com/MyHello/sayHelloRequest", output = "helloservice.ws.helen.com/MyHello/sayHelloResponse")
    public String sayHello(
            @WebParam(name = "username", targetNamespace = "")
                    String username);

}
