
package com.helen.ws.personservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyPersonServer", targetNamespace = "personservice.ws.helen.com", wsdlLocation = "http://127.0.0.1:8090/person?wsdl")
public class MyPersonServer
    extends Service
{

    private final static URL MYPERSONSERVER_WSDL_LOCATION;
    private final static WebServiceException MYPERSONSERVER_EXCEPTION;
    private final static QName MYPERSONSERVER_QNAME = new QName("personservice.ws.helen.com", "MyPersonServer");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8090/person?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYPERSONSERVER_WSDL_LOCATION = url;
        MYPERSONSERVER_EXCEPTION = e;
    }

    public MyPersonServer() {
        super(__getWsdlLocation(), MYPERSONSERVER_QNAME);
    }

    public MyPersonServer(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYPERSONSERVER_QNAME, features);
    }

    public MyPersonServer(URL wsdlLocation) {
        super(wsdlLocation, MYPERSONSERVER_QNAME);
    }

    public MyPersonServer(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYPERSONSERVER_QNAME, features);
    }

    public MyPersonServer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyPersonServer(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MyPerson
     */
    @WebEndpoint(name = "MyPersonPort")
    public MyPerson getMyPersonPort() {
        return super.getPort(new QName("personservice.ws.helen.com", "MyPersonPort"), MyPerson.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyPerson
     */
    @WebEndpoint(name = "MyPersonPort")
    public MyPerson getMyPersonPort(WebServiceFeature... features) {
        return super.getPort(new QName("personservice.ws.helen.com", "MyPersonPort"), MyPerson.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYPERSONSERVER_EXCEPTION!= null) {
            throw MYPERSONSERVER_EXCEPTION;
        }
        return MYPERSONSERVER_WSDL_LOCATION;
    }

}
